### ISSUE TITLE
IP Bans, Failed Logins

### ISSUE THREAD

**Issue by jazzyisj** [jazzyisj/home-assistant-config#16]
- Prevents http_ban usage
- Temporary fix for notifications - auto dismiss

```
- id: hass_dismiss_failed_login_notification
  alias: '[Hass] Dismiss Failed Login Notfication'
  description: 'Automatically dismiss failed login notifications.'
  mode: restart
  trigger:
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: persistent_notification.http_login
  condition:
    - condition: template
      value_template: "{{ states('persistent_notification.http_login') == 'notifying' }}"
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: http_login
```
