### ISSUE TITLE
Mobile App - High Accuracy Mode sensor not turning on

### ISSUE THREAD

**Issue by jazzyisj** [jazzyisj/home-assistant-config#34]
High Accuracy Mode binary sensor does not turn on when high_accuracy command sent from HA

```
    - service: "notify.jason"
      data:
        message: command_high_accuracy_mode  
        title: turn_on
```
Cannot use for alert or to turn off high accuracy mode.
