### ISSUE TITLE
Lovelace: state-switch deviceID not working

### ISSUE THREAD

**Issue by jazzyisj** [jazzyisj/home-assistant-config#42]
#SWITCH https://github.com/thomasloven/lovelace-state-switch/issues/90

```
  - type: custom:state-switch
    entity: deviceID #SWITCH
    default: "jlaptop_chrome_internal"
    states:
      kiosk_internal: ...
      jlaptop_chrome_internal: ...
```

**Comment by pickonedev** [comment]
Still not working.... after more than one year...

I used the sample from the documentation, just replaced the device IDs

```
type: custom:state-switch
entity: deviceID
states:
  e7d9f6b5-56c2c14a:
    type: markdown
    content: |
      Desktop
  e7d9f6b5-56c2ffaa:
    type: markdown
    content: |
      Mobile
```
