### ISSUE TITLE
Lovelace - browser_mod browserID not working

### ISSUE THREAD

**Issue by jazzyisj** [jazzyisj/home-assistant-config#43]
#BROWSER   https://github.com/thomasloven/hass-browser_mod/issues/405

```
- service: browser_mod.refresh # browserID not working
  target:
    device_id:
      - 844e8df7e589372a13ee7d6a638afb79 # jlaptop_chrome_internal
      - fc623248cd06a99fc15113a2fec6be59 # jlaptop_chrome_external
      - 6c7bbd2608a05e4e4727e8cfe4f29442 # jphone_app_external
      - 042346b1d9f172f19ef21a3bdac9d22b # jphone_app_internal
      - eeb78bb5da847dd9bd8b107b91106f9c # kiosk_internal
```
